[package]
name = "span"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "2.0.3"
serde_json = "1.0.114"
lazy_static = "1.4.0"
