name: Rust CI (merge on main)

on:
  push:
    branches:
      - cantseeme

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  ci:
    runs-on:
      - self-hosted
    container:
      image: ghcr.io/ryse-rs/gh_runner_rust:latest
      options: --log-level=debug --privileged -v /sys/fs/cgroup:/sys/fs/cgroup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        id: cargo_cache
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          cargo install cargo-audit
          cargo install cargo-outdated
          cargo install cargo-machete

      - name: Display informations (rust, cargo)
        shell: bash
        run: |
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: vulnerabilities
        run: cargo audit

      - name: release build
        run: cargo build --release

      - name: unit tests
        run: cargo test --all-features --verbose

      - name: format
        if: ${{ ! cancelled() }}
        run: cargo fmt --all -- --check

      - name: lints
        if: ${{ ! cancelled() }}
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: outdated dependencies
        if: ${{ ! cancelled() }}
        run: cargo outdated --format json

      - name: unused dependencies (warn)
        if: ${{ ! cancelled() }}
        run: cargo machete
