name: Rust CI (merge on main)

on:
  push:
    branches:
      - 20-enhance-update-to-self-hosted-actions-runners

jobs:
  test:
    runs-on: self-hosted
    container:
      image: alpine:latest
      options: --privileged
    steps:
      - name: Test container
        run: |
          echo "Container is running"
          cat /proc/1/cgroup
