name: Rust CI (merge on main)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  ci:
    runs-on:
      - self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # - uses: mozilla-actions/sccache-action@v0.0.5
      # - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v4
        id: cargo_cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Display informations (rust, cargo)
        shell: bash
        run: |
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: vulnerabilities
        run: |
          cargo install cargo-audit
          cargo audit

      - name: format
        if: always()
        run: cargo fmt --all -- --check

      - name: release build
        if: always()
        run: cargo build --release

      - name: lints
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: unit tests
        run: cargo test --all-features --verbose

      - name: outdated dependencies
        if: always()
        run: |
          cargo install cargo-outdated
          cargo outdated --format json

      - name: unused dependencies (warn)
        if: always()
        continue-on-error: true
        run: |
          cargo install cargo-machete
          cargo machete
