name: Rust CI (PR)

on:
  pull_request:
    types: [ready_for_review, synchronize]
    branches: ["**"]
    paths:
      - "**.rs"
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v4
        id: cargo_cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Display informations (rust, cargo)
        shell: bash
        run: |
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: vulnerabilities
        run: cargo audit

      - name: format
        if: always()
        run: cargo fmt --all -- --check

      - name: release build
        if: always()
        run: cargo build --release

      - name: lints
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: unit tests
        run: cargo test --all-features --verbose

      - name: outdated dependencies
        if: always()
        run: cargo outdated --format json
